server.port: 8080

spring.application.name: springcloud-nacos-consumer

spring.cloud.nacos.discovery.server-addr: nacos-server.hsb.cn:8848

management.endpoints.web.exposure.include: "*"

#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000